dbfilename redis_queue.rdb
dir /mnt/d/code/frappe_dev/my-bench/config/pids
pidfile /mnt/d/code/frappe_dev/my-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /mnt/d/code/frappe_dev/my-bench/config/redis_queue.acl
